<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <AssemblyName>DevExpress.Pdf.v25.2.Core</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <RootNamespace>DevExpress.Pdf</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <OutputPath>..\DevExpress.Dll\Framework\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="LocalizationRes.ar.resx" />
    <EmbeddedResource Include="LocalizationRes.bg.resx" />
    <EmbeddedResource Include="LocalizationRes.ca.resx" />
    <EmbeddedResource Include="LocalizationRes.cs.resx" />
    <EmbeddedResource Include="LocalizationRes.da.resx" />
    <EmbeddedResource Include="LocalizationRes.de-CH.resx" />
    <EmbeddedResource Include="LocalizationRes.de.resx" />
    <EmbeddedResource Include="LocalizationRes.el.resx" />
    <EmbeddedResource Include="LocalizationRes.es.resx" />
    <EmbeddedResource Include="LocalizationRes.fa.resx" />
    <EmbeddedResource Include="LocalizationRes.fi.resx" />
    <EmbeddedResource Include="LocalizationRes.fr.resx" />
    <EmbeddedResource Include="LocalizationRes.he.resx" />
    <EmbeddedResource Include="LocalizationRes.hr.resx" />
    <EmbeddedResource Include="LocalizationRes.hu.resx" />
    <EmbeddedResource Include="LocalizationRes.hy.resx" />
    <EmbeddedResource Include="LocalizationRes.is.resx" />
    <EmbeddedResource Include="LocalizationRes.it.resx" />
    <EmbeddedResource Include="LocalizationRes.ja.resx" />
    <EmbeddedResource Include="LocalizationRes.ko.resx" />
    <EmbeddedResource Include="LocalizationRes.lt.resx" />
    <EmbeddedResource Include="LocalizationRes.lv.resx" />
    <EmbeddedResource Include="LocalizationRes.mk.resx" />
    <EmbeddedResource Include="LocalizationRes.nl.resx" />
    <EmbeddedResource Include="LocalizationRes.no.resx" />
    <EmbeddedResource Include="LocalizationRes.pl.resx" />
    <EmbeddedResource Include="LocalizationRes.pt-BR.resx" />
    <EmbeddedResource Include="LocalizationRes.pt.resx" />
    <EmbeddedResource Include="LocalizationRes.resx" />
    <EmbeddedResource Include="LocalizationRes.ro.resx" />
    <EmbeddedResource Include="LocalizationRes.ru.resx" />
    <EmbeddedResource Include="LocalizationRes.sk.resx" />
    <EmbeddedResource Include="LocalizationRes.sl.resx" />
    <EmbeddedResource Include="LocalizationRes.sr-Cyrl-RS.resx" />
    <EmbeddedResource Include="LocalizationRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="LocalizationRes.sr-Latn-RS.resx" />
    <EmbeddedResource Include="LocalizationRes.sv.resx" />
    <EmbeddedResource Include="LocalizationRes.ta.resx" />
    <EmbeddedResource Include="LocalizationRes.tr.resx" />
    <EmbeddedResource Include="LocalizationRes.uk.resx" />
    <EmbeddedResource Include="LocalizationRes.vi.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-CN.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-Hans.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-Hant.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-TW.resx" />
    <EmbeddedResource Include="LocalizationRes.et.resx" />
    <EmbeddedResource Include="LocalizationRes.hi.resx" />
    <EmbeddedResource Include="LocalizationRes.id.resx" />
    <EmbeddedResource Include="LocalizationRes.kk.resx" />
    <EmbeddedResource Include="LocalizationRes.ms.resx" />
    <EmbeddedResource Include="LocalizationRes.th.resx" />
    <EmbeddedResource Include="LocalizationRes.nb-NO.resx" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>
</Project>