<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DevExpress.AIIntegration.WinForms.v25.2</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <RootNamespace>DevExpress.AIIntegration.WinForms</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net472'">
    <OutputPath>..\DevExpress.Dll\Framework\</OutputPath>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Controls\AIRequestControl.de.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Reporting\DocumentAIOperationForm.de.resx">
      <DependentUpon>DocumentAIOperationForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Reporting\DocumentAIOperationForm.resx">
      <DependentUpon>DocumentAIOperationForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ar.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.bg.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ca.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.cs.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.da.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.el.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.es.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.et.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.fa.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.fi.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.fr.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.he.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.hi.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.hr.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.hu.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.hy.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.id.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.is.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.it.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ja.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.kk.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ko.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.lt.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.lv.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.mk.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ms.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.nl.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.no.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.pl.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.pt.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ro.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ru.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.sk.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.sl.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.sv.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.ta.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.th.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.tr.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.uk.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.vi.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.de-CH.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.pt-BR.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.sr-Cyrl-RS.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.sr-Latn-BA.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.sr-Latn-RS.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.zh-CN.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.zh-Hans.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.zh-Hant.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.zh-TW.resx">
      <DependentUpon>AIRequestControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Controls\AIRequestControl.nb-NO.resx" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="AssemblyInfo.cs" />
    <Compile Include="Controls\AIRequestControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="Reporting\DocumentAIOperationForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
</Project>