<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DevExpress.DataAccess.v25.2.UI</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <RootNamespace>DevExpress.DataAccess.UI</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <OutputPath>..\DevExpress.Dll\Framework\</OutputPath>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ar.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.bg.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ca.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.cs.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.da.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.de-CH.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.de.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.el.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.es.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.fa.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.fi.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.fr.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.he.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.hr.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.hu.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.hy.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.is.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.it.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ja.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ko.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.lt.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.lv.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.mk.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.nl.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.no.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.pl.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.pt-BR.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.pt.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ro.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ru.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.sk.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.sl.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.sr-Cyrl-RS.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.sr-Latn-BA.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.sr-Latn-RS.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.sv.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ta.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.tr.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.uk.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.vi.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.zh-CN.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.zh-Hans.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.zh-Hant.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.zh-TW.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.et.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.hi.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.id.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.kk.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.ms.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.th.resx">
      <DependentUpon>ConnectionNameControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Native\Sql\DataConnectionControls\ConnectionNameControl.nb-NO.resx" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Native\Sql\DataConnectionControls\ConnectionNameControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
  </ItemGroup>
</Project>