<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DevExpress.EntityFrameworkCore.Security.v26.1</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>DevExpress.EntityFrameworkCore.Security</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <OutputPath>..\DevExpress.Dll\Framework\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Messages.ID.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Messages.ar.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.bg.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.ca.resx" />
    <EmbeddedResource Include="Messages.cs.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.da.resx" />
    <EmbeddedResource Include="Messages.de-CH.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.de.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.el.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.es.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.et.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.fa.resx" />
    <EmbeddedResource Include="Messages.fi.resx" />
    <EmbeddedResource Include="Messages.fr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.he.resx" />
    <EmbeddedResource Include="Messages.hr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.hu.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.hy.resx" />
    <EmbeddedResource Include="Messages.is.resx" />
    <EmbeddedResource Include="Messages.it.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.ja.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.ko.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.lt.resx" />
    <EmbeddedResource Include="Messages.lv.resx" />
    <EmbeddedResource Include="Messages.mk.resx" />
    <EmbeddedResource Include="Messages.nl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.no.resx" />
    <EmbeddedResource Include="Messages.pl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.pt-BR.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.pt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.ro.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.ru.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.sk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.sl.resx" />
    <EmbeddedResource Include="Messages.sr-Cyrl-RS.resx" />
    <EmbeddedResource Include="Messages.sr-Latn-BA.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.sr-Latn-RS.resx" />
    <EmbeddedResource Include="Messages.sv.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.ta.resx" />
    <EmbeddedResource Include="Messages.tr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.uk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.vi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.zh-CN.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.zh-Hans.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.zh-Hant.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.zh-TW.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Messages.hi.resx" />
    <EmbeddedResource Include="Messages.id.resx" />
    <EmbeddedResource Include="Messages.kk.resx" />
    <EmbeddedResource Include="Messages.ms.resx" />
    <EmbeddedResource Include="Messages.th.resx" />
    <EmbeddedResource Include="Messages.af.resx" />
    <EmbeddedResource Include="Messages.az.resx" />
    <EmbeddedResource Include="Messages.bs.resx" />
    <EmbeddedResource Include="Messages.cy.resx" />
    <EmbeddedResource Include="Messages.en-GB.resx" />
    <EmbeddedResource Include="Messages.es-MX.resx" />
    <EmbeddedResource Include="Messages.ka.resx" />
    <EmbeddedResource Include="Messages.mn-MN.resx" />
    <EmbeddedResource Include="Messages.nb-NO.resx" />
    <EmbeddedResource Include="Messages.sq.resx" />
    <EmbeddedResource Include="Messages.sr-Latn-ME.resx" />
    <EmbeddedResource Include="Messages.ur.resx" />
    <EmbeddedResource Include="Messages.uz-Cyrl-UZ.resx" />
    <EmbeddedResource Include="Messages.uz-Latn-UZ.resx" />
    <EmbeddedResource Include="Messages.ky.resx" />
  </ItemGroup>
</Project>
