<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DevExpress.Printing.v26.1.Core</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>DevExpress.XtraPrinting</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <OutputPath>..\DevExpress.Dll\Framework\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DescriptionsRes.de.resx" />
    <EmbeddedResource Include="ErrorStringId.de.resx" />
    <EmbeddedResource Include="PropertyNamesRes.et.resx" />
    <EmbeddedResource Include="PropertyNamesRes.hi.resx" />
    <EmbeddedResource Include="PropertyNamesRes.id.resx" />
    <EmbeddedResource Include="PropertyNamesRes.kk.resx" />
    <EmbeddedResource Include="PropertyNamesRes.ms.resx" />
    <EmbeddedResource Include="PropertyNamesRes.th.resx" />
    <EmbeddedResource Include="PropertyNamesRes.zh-TW.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.zh-Hant.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.uk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.sr-Latn-BA.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.mk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.lv.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.lt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.ko.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.is.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.hy.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.el.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.de-CH.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.ar.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.bg.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.ca.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.cs.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.da.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.de.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.es.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.fa.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.fi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.fr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.he.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.hr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.hu.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.it.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.ja.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.nl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.no.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.nb-NO.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.pl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.pt-BR.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.pt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.ro.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.ru.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.sk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.sl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.sr-Cyrl-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.sr-Latn-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.sv.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.ta.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.tr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.vi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.zh-Hans.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertyNamesRes.zh-CN.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="ErrorStringId.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="DescriptionsRes.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="DescriptionsRes.af.resx" />
    <EmbeddedResource Include="DescriptionsRes.az.resx" />
    <EmbeddedResource Include="DescriptionsRes.bs.resx" />
    <EmbeddedResource Include="DescriptionsRes.cy.resx" />
    <EmbeddedResource Include="DescriptionsRes.en-GB.resx" />
    <EmbeddedResource Include="DescriptionsRes.es-MX.resx" />
    <EmbeddedResource Include="DescriptionsRes.ka.resx" />
    <EmbeddedResource Include="DescriptionsRes.mn-MN.resx" />
    <EmbeddedResource Include="DescriptionsRes.sq.resx" />
    <EmbeddedResource Include="DescriptionsRes.sr-Latn-ME.resx" />
    <EmbeddedResource Include="DescriptionsRes.ur.resx" />
    <EmbeddedResource Include="DescriptionsRes.uz-Cyrl-UZ.resx" />
    <EmbeddedResource Include="DescriptionsRes.uz-Latn-UZ.resx" />
    <EmbeddedResource Include="DescriptionsRes.ky.resx" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
