<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>DevExpress.Persistent.Base.v26.1</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>DevExpress.Persistent.Base</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\PropertyNamesRes.ar.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.bg.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ca.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.cs.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.da.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.de-CH.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.de.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.el.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.es.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.et.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.fa.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.fi.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.fr.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.he.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.hr.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.hu.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.hy.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.is.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.it.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ja.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ko.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.lt.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.lv.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.mk.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.nl.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.no.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.pl.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.pt-BR.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.pt.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ro.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ru.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\PropertyNamesRes.sk.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.sl.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.sr-Cyrl-RS.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.sr-Latn-RS.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.sv.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ta.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.tr.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.uk.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.vi.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.zh-CN.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.zh-Hans.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.zh-Hant.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.zh-TW.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.id.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.kk.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ms.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.af.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.az.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.bs.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.cy.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.en-GB.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.es-MX.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ka.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.mn-MN.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.nb-NO.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.sq.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.sr-Latn-ME.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ur.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.uz-Cyrl-UZ.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.uz-Latn-UZ.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.ky.resx" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\PropertyNamesRes.hi.resx" />
    <EmbeddedResource Include="Resources\PropertyNamesRes.th.resx" />
  </ItemGroup>
</Project>
