<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DevExpress.Web.v26.1</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>DevExpress.Web</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\DevExpress.Dll\Framework\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Common\LocalizationRes.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ar.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.az.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.bg.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.ca.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.cs.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.da.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.de-CH.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.de.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.el.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.es.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.et.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.fa.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.fi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.fr.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.he.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.hi.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.hr.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.hu.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.hy.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.id.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.is.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.it.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ja.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.kk.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ko.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.lt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.lv.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.mk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.ms.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.nl.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.no.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.pl.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.pt-BR.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.pt.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ro.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ru.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.sk.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.sl.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.sr-Cyrl-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.sr-Latn-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.sv.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ta.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.th.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.tr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.uk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.vi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.zh-CN.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.zh-Hans.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.zh-Hant.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Common\LocalizationRes.zh-TW.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.az.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.et.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.hi.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.th.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.et.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.hi.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.th.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.zh-TW.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.zh-CN.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.vi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.uk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.tr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.ta.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.sr-Latn-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.sr-Cyrl-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.pt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.mk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.lt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.ko.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.hy.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.he.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.fi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.fa.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.de-CH.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.ca.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.bg.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.zh-TW.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.zh-CN.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.vi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.uk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.tr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.ta.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.sr-Latn-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.sr-Cyrl-RS.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.pt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.mk.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.lt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.ko.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.is.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.hy.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.he.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.fi.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.fa.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.de-CH.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.ca.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.bg.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Grid\LocalizationRes.zh-Hant.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.zh-Hant.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Edit\LocalizationRes.ar.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.cs.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.da.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.de.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.el.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.es.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.fr.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.hr.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.hu.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.it.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.ja.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.lv.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.nl.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.no.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.nb-NO.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.pl.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.pt-BR.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.ro.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.ru.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.sk.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.sl.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.sv.resx" />
    <EmbeddedResource Include="Edit\LocalizationRes.zh-Hans.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.ar.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.cs.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.da.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.de.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.el.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.es.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.fr.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.hr.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.hu.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.is.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.it.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.ja.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.lv.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.nl.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.no.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.nb-NO.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.pl.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.pt-BR.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.ro.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.ru.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.sk.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.sl.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.sv.resx" />
    <EmbeddedResource Include="Grid\LocalizationRes.zh-Hans.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.af.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.bs.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.cy.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.en-GB.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.es-MX.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ka.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.mn-MN.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.nb-NO.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.sq.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.sr-Latn-ME.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ur.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.uz-Cyrl-UZ.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.uz-Latn-UZ.resx" />
    <EmbeddedResource Include="Common\LocalizationRes.ky.resx" />
  </ItemGroup>
</Project>
