<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DevExpress.Sparkline.v26.1.Core</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>DevExpress.Sparkline</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <OutputPath>..\DevExpress.Dll\Framework\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DescriptionsRes.de.resx" />
    <EmbeddedResource Include="LocalizationRes.ar.resx" />
    <EmbeddedResource Include="LocalizationRes.ca.resx" />
    <EmbeddedResource Include="LocalizationRes.cs.resx" />
    <EmbeddedResource Include="LocalizationRes.da.resx" />
    <EmbeddedResource Include="LocalizationRes.de-CH.resx" />
    <EmbeddedResource Include="LocalizationRes.de.resx" />
    <EmbeddedResource Include="LocalizationRes.el.resx" />
    <EmbeddedResource Include="LocalizationRes.es.resx" />
    <EmbeddedResource Include="LocalizationRes.fa.resx" />
    <EmbeddedResource Include="LocalizationRes.fi.resx" />
    <EmbeddedResource Include="LocalizationRes.fr.resx" />
    <EmbeddedResource Include="LocalizationRes.he.resx" />
    <EmbeddedResource Include="LocalizationRes.hr.resx" />
    <EmbeddedResource Include="LocalizationRes.hu.resx" />
    <EmbeddedResource Include="LocalizationRes.it.resx" />
    <EmbeddedResource Include="LocalizationRes.ja.resx" />
    <EmbeddedResource Include="LocalizationRes.ko.resx" />
    <EmbeddedResource Include="LocalizationRes.nl.resx" />
    <EmbeddedResource Include="LocalizationRes.no.resx" />
    <EmbeddedResource Include="LocalizationRes.nb-NO.resx" />
    <EmbeddedResource Include="LocalizationRes.pl.resx" />
    <EmbeddedResource Include="LocalizationRes.pt-BR.resx" />
    <EmbeddedResource Include="LocalizationRes.pt.resx" />
    <EmbeddedResource Include="LocalizationRes.ro.resx" />
    <EmbeddedResource Include="LocalizationRes.ru.resx" />
    <EmbeddedResource Include="LocalizationRes.resx" />
    <EmbeddedResource Include="LocalizationRes.sk.resx" />
    <EmbeddedResource Include="LocalizationRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="LocalizationRes.sv.resx" />
    <EmbeddedResource Include="LocalizationRes.ta.resx" />
    <EmbeddedResource Include="LocalizationRes.tr.resx" />
    <EmbeddedResource Include="LocalizationRes.uk.resx" />
    <EmbeddedResource Include="LocalizationRes.vi.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-CN.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-Hans.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-Hant.resx" />
    <EmbeddedResource Include="LocalizationRes.zh-TW.resx" />
    <EmbeddedResource Include="PropertyNamesRes.ar.resx" />
    <EmbeddedResource Include="PropertyNamesRes.bg.resx" />
    <EmbeddedResource Include="PropertyNamesRes.ca.resx" />
    <EmbeddedResource Include="PropertyNamesRes.cs.resx" />
    <EmbeddedResource Include="PropertyNamesRes.da.resx" />
    <EmbeddedResource Include="PropertyNamesRes.de-CH.resx" />
    <EmbeddedResource Include="PropertyNamesRes.de.resx" />
    <EmbeddedResource Include="PropertyNamesRes.el.resx" />
    <EmbeddedResource Include="PropertyNamesRes.es.resx" />
    <EmbeddedResource Include="PropertyNamesRes.et.resx" />
    <EmbeddedResource Include="PropertyNamesRes.fa.resx" />
    <EmbeddedResource Include="PropertyNamesRes.fi.resx" />
    <EmbeddedResource Include="PropertyNamesRes.fr.resx" />
    <EmbeddedResource Include="PropertyNamesRes.he.resx" />
    <EmbeddedResource Include="PropertyNamesRes.hr.resx" />
    <EmbeddedResource Include="PropertyNamesRes.hu.resx" />
    <EmbeddedResource Include="PropertyNamesRes.it.resx" />
    <EmbeddedResource Include="PropertyNamesRes.ja.resx" />
    <EmbeddedResource Include="PropertyNamesRes.ko.resx" />
    <EmbeddedResource Include="PropertyNamesRes.nl.resx" />
    <EmbeddedResource Include="PropertyNamesRes.no.resx" />
    <EmbeddedResource Include="PropertyNamesRes.nb-NO.resx" />
    <EmbeddedResource Include="PropertyNamesRes.pl.resx" />
    <EmbeddedResource Include="PropertyNamesRes.pt-BR.resx" />
    <EmbeddedResource Include="PropertyNamesRes.pt.resx" />
    <EmbeddedResource Include="PropertyNamesRes.resx" />
    <EmbeddedResource Include="PropertyNamesRes.ro.resx" />
    <EmbeddedResource Include="PropertyNamesRes.ru.resx" />
    <EmbeddedResource Include="PropertyNamesRes.sk.resx" />
    <EmbeddedResource Include="PropertyNamesRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="PropertyNamesRes.sv.resx" />
    <EmbeddedResource Include="PropertyNamesRes.tr.resx" />
    <EmbeddedResource Include="PropertyNamesRes.uk.resx" />
    <EmbeddedResource Include="PropertyNamesRes.vi.resx" />
    <EmbeddedResource Include="PropertyNamesRes.zh-CN.resx" />
    <EmbeddedResource Include="PropertyNamesRes.zh-Hans.resx" />
    <EmbeddedResource Include="PropertyNamesRes.zh-Hant.resx" />
    <EmbeddedResource Include="PropertyNamesRes.zh-TW.resx" />
    <EmbeddedResource Include="DescriptionsRes.resx" />
    <EmbeddedResource Include="DescriptionsRes.hi.resx" />
    <EmbeddedResource Include="DescriptionsRes.hy.resx" />
    <EmbeddedResource Include="DescriptionsRes.id.resx" />
    <EmbeddedResource Include="DescriptionsRes.is.resx" />
    <EmbeddedResource Include="DescriptionsRes.kk.resx" />
    <EmbeddedResource Include="DescriptionsRes.lt.resx" />
    <EmbeddedResource Include="DescriptionsRes.lv.resx" />
    <EmbeddedResource Include="DescriptionsRes.mk.resx" />
    <EmbeddedResource Include="DescriptionsRes.ms.resx" />
    <EmbeddedResource Include="DescriptionsRes.sl.resx" />
    <EmbeddedResource Include="DescriptionsRes.th.resx" />
    <EmbeddedResource Include="DescriptionsRes.sr-Cyrl-RS.resx" />
    <EmbeddedResource Include="DescriptionsRes.sr-Latn-RS.resx" />
    <EmbeddedResource Include="DescriptionsRes.af.resx" />
    <EmbeddedResource Include="DescriptionsRes.az.resx" />
    <EmbeddedResource Include="DescriptionsRes.bs.resx" />
    <EmbeddedResource Include="DescriptionsRes.cy.resx" />
    <EmbeddedResource Include="DescriptionsRes.en-GB.resx" />
    <EmbeddedResource Include="DescriptionsRes.es-MX.resx" />
    <EmbeddedResource Include="DescriptionsRes.ka.resx" />
    <EmbeddedResource Include="DescriptionsRes.mn-MN.resx" />
    <EmbeddedResource Include="DescriptionsRes.sq.resx" />
    <EmbeddedResource Include="DescriptionsRes.sr-Latn-ME.resx" />
    <EmbeddedResource Include="DescriptionsRes.ur.resx" />
    <EmbeddedResource Include="DescriptionsRes.uz-Cyrl-UZ.resx" />
    <EmbeddedResource Include="DescriptionsRes.uz-Latn-UZ.resx" />
    <EmbeddedResource Include="DescriptionsRes.ky.resx" />
  </ItemGroup>
</Project>
