<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>DevExpress.Blazor.PivotTable.v26.1</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>DevExpress.Blazor.PivotTable</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\LocalizationRes.de.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ar.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.bg.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ca.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.cs.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.da.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.el.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.es.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.et.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.fa.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.fi.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.fr.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.he.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.hi.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.hr.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.hu.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.hy.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.id.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.is.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.it.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ja.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.kk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ko.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.lt.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.lv.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.mk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ms.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.nl.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.no.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.pl.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.pt.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ro.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ru.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sl.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sv.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ta.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.th.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.tr.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.uk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.vi.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.de-CH.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.pt-BR.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sr-Cyrl-RS.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sr-Latn-RS.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-CN.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-Hans.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-Hant.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-TW.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.af.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.az.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.bs.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.cy.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.en-GB.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.es-MX.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ka.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.mn-MN.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.nb-NO.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sq.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sr-Latn-ME.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ur.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.uz-Cyrl-UZ.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.uz-Latn-UZ.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ky.resx" />
  </ItemGroup>
</Project>
