<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>DevExpress.Blazor.RichEdit.v25.2</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <RootNamespace>DevExpress.Blazor.RichEdit</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\DevExpress.Dll\NETCore\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\LocalizationRes.ar.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.bg.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ca.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.cs.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.da.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.de-CH.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.de.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.el.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.es.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\LocalizationRes.et.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.fa.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.fi.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.fr.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.he.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.hi.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.hr.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.hu.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\LocalizationRes.hy.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.is.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.it.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ja.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ko.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.lt.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.lv.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.mk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.nl.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.no.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.pl.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.pt-BR.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.pt.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\LocalizationRes.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\LocalizationRes.ro.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ru.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\LocalizationRes.sk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sl.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sr-Cyrl-RS.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sr-Latn-BA.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sr-Latn-RS.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.sv.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ta.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.th.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.tr.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.uk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.vi.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-CN.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-Hans.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-Hant.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.zh-TW.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.id.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.kk.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.ms.resx" />
    <EmbeddedResource Include="Resources\LocalizationRes.nb-NO.resx" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyVersion.cs">
      <Link>AssemblyVersion.cs</Link>
    </Compile>
    <Compile Include="AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>